// AUTO-GENERATED by scripts/embed-assets.ts — do not edit.
/** Embedded web/dist assets (path -> base64). Empty when running from source. */
export const EMBEDDED_ASSETS: Record<string, string> = {};
