/**
 * Generates packages/server/src/assets.ts by inlining everything in apps/web/dist as
 * base64. This lets `bun build --compile` produce a true single-file binary
 * with the dashboard UI embedded. Run via `bun run scripts/embed-assets.ts`
 * after building the web app.
 */
import {
	existsSync,
	readdirSync,
	readFileSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";

const distDir = join(import.meta.dir, "../apps/web/dist");
const outFile = join(import.meta.dir, "../packages/server/src/assets.ts");

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) out.push(...walk(full));
		else out.push(full);
	}
	return out;
}

// Guard: without a built apps/web/dist there's nothing to embed. Write an empty stub
// (valid for source/dev runs) and bail rather than crashing — the real bundle is
// produced once `build:web` has populated apps/web/dist.
if (!existsSync(distDir)) {
	writeFileSync(
		outFile,
		`// AUTO-GENERATED by scripts/embed-assets.ts — do not edit.
/** Empty stub: apps/web/dist was absent at embed time (run build:web first). */
export const EMBEDDED_ASSETS: Record<string, string> = {};
`,
	);
	console.warn(
		`embed-assets: apps/web/dist not found — wrote empty stub at ${relative(process.cwd(), outFile)}`,
	);
	process.exit(0);
}

const files = walk(distDir);
const entries: string[] = [];
for (const f of files) {
	const rel = `/${relative(distDir, f).split("\\").join("/")}`;
	const b64 = readFileSync(f).toString("base64");
	entries.push(`  ${JSON.stringify(rel)}: ${JSON.stringify(b64)},`);
}

const content = `// AUTO-GENERATED by scripts/embed-assets.ts — do not edit.
/** Embedded apps/web/dist assets (path -> base64). Empty when running from source. */
export const EMBEDDED_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(outFile, content);
console.log(
	`Embedded ${files.length} asset(s) into ${relative(process.cwd(), outFile)}`,
);
