/**
 * Ensures src/server/assets.gen.ts exists so the project type-checks, runs from
 * source, and tests on a fresh clone WITHOUT a full web build.
 *
 * assets.gen.ts is a generated artifact (gitignored — see issue #20) produced by
 * embed-assets.ts from web/dist. It's imported at runtime by server/index.ts, so
 * it must exist for `tsc`, `bun test`, and `bun run dev`. The real binary build
 * (`bun run build`/`build:targets`) overwrites it with the full base64 bundle via
 * `embed`; for everything else an empty stub is correct — source/dev runs serve
 * the UI from web/dist on disk, not from EMBEDDED_ASSETS.
 *
 * Idempotent: leaves an existing (real or stub) file untouched.
 */
import { existsSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const outFile = join(import.meta.dir, "../src/server/assets.gen.ts");

const STUB = `// AUTO-GENERATED by scripts/ensure-assets.ts — do not edit.
/** Empty stub for source/dev runs; the real bundle is written by embed-assets.ts at build time. */
export const EMBEDDED_ASSETS: Record<string, string> = {};
`;

if (existsSync(outFile)) {
  // Already present (real bundle or a prior stub) — nothing to do.
  process.exit(0);
}

writeFileSync(outFile, STUB);
console.log(`Wrote empty assets stub at ${relative(process.cwd(), outFile)}`);
