/**
 * Generates src/version.gen.ts from package.json so the compiled binary has a
 * single source of truth for its version. Run before `bun build --compile`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const pkgPath = join(import.meta.dir, "../package.json");
const outFile = join(import.meta.dir, "../src/version.gen.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const version: string = pkg.version ?? "0.0.0";

const content = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit.
/** Version baked in at build time, sourced from package.json. */
export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(outFile, content);
console.log(
	`Wrote version ${version} into ${relative(process.cwd(), outFile)}`,
);
